# Copyright 2018 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

# defines the default content repository
content: https://github.com/adobe/project-helix.io.git

# defines the default code (and static) repository
code: https://github.com/adobe/project-helix.io.git

# defines the default static root relative to the code repository
staticRoot: /webroot

# defines the directory index file
directoryIndex: index.html

strains:
  default:
    code: /acapt/default/https---github-com-adobe-project-helix-io-git--master--
    url: https://www.project-helix.io
    content:
      repo: project-helix.io
      ref: master
      owner: adobe

  client:
    code: /acapt/default/https---github-com-adobe-project-helix-io-git--master--
    url: https://client.project-helix.io
    content:
      repo: helix-cli
      ref: master
      owner: adobe

  pipeline:
    code: /acapt/default/https---github-com-adobe-project-helix-io-git--master--
    url: https://pipeline.project-helix.io
    content:
      repo: hypermedia-pipeline
      ref: master
      owner: adobe
